kafka:
  consumer-group: group-1
  topic:
    logging-requests: "training-builder-topic"

#spring:
#  kafka:
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
server:
  port: 8081
